import Head from 'next/head';
import {Inter} from 'next/font/google';
import styles from '@/styles/Home.module.css';
import {signIn, signOut, useSession} from 'next-auth/react';

const inter = Inter({subsets: ['latin']});

export default function Home() {
  const session = useSession();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        {session.status === 'loading' ? (
          <p>loading...</p>
        ) : session.status === 'authenticated' ? (
          <div>
            <p>{JSON.stringify(session, null, 2)}</p>
            <button onClick={() => signOut()}>sign out</button>
          </div>
        ) : (
          <div>
            <p>not authenticated</p>
            <button onClick={() => signIn()}>sign in</button>
          </div>
        )}
      </main>
    </>
  );
}
